import Head from 'next/head'
import Image from 'next/image'
import logoCircle from "../public/logoCircle.png";

export default function Home() {
  return (
    <>
      <Head>
        <title>Dbarlits</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Image
        alt="Dbarlits logo"
        src={logoCircle}
        width={300}
        height={300}
        style={{
          maxWidth: "100%",
          height: "auto",
        }}
      />
    </>
  );
}
